package main.ast;

public enum NodeKind {
    CHUNK,

    // statements
    BLOCK,
    ASSIGNMENT_STATEMENT,
    LOCAL_STATEMENT,
    LOCAL_FUNCTION_STATEMENT,
    FUNCTION_STATEMENT,
    RETURN_STATEMENT,
    BREAK_STATEMENT,
    CONTINUE_STATEMENT,
    EXPRESSION_STATEMENT,

    // control flow statements
    DO_STATEMENT,
    IF_STATEMENT,
    ELSEIF_STATEMENT,
    ELSE_STATEMENT,
    WHILE_STATEMENT,
    REPEAT_STATEMENT,
    FOR_NUMERIC_STATEMENT,
    FOR_GENERIC_STATEMENT,


    // expressions
    IDENTIFIER,
    LITERAL,
    BINARY,
    UNARY,
    FUNCTION_CALL,
    VARARG,
    TABLE_CONSTRUCTOR,
    ANONYMOUS_FUNCTION,
    TABLE_FIELD,
    PARENTHESIS_EXPRESSION, //parenthesis
    METHOD_CALL,
    METHOD_DEFINITION,

}